services:
  postgres_db:
    image: postgres:15-alpine
    container_name: db_final_uaq
    environment:
      POSTGRES_USER: admin_taller
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bd_tickets_final
      POSTGRES_HOST_AUTH_METHOD: trust 
    ports:
      - "5435:5432"
    volumes:
      - vol_final_uaq:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chihuahueno_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5435
      - DB_USER=admin_taller
      - DB_PASSWORD=password123
      - DB_NAME=bd_tickets_final
    depends_on:
      - postgres_db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chihuahueno_frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  vol_final_uaq:

networks:
  app-network:
    driver: bridge
